doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: 'mongodb://root:password@mongodb_casfid_technical_test:27017'
            options:
                authSource: admin
    default_database: casfid_technical_test
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Domain/Entity'
                    prefix: 'App\Domain\Entity'
                    alias: App